### ISSUE TITLE
Having trouble parsing data file ./docs/_merged_data/footer.json

### ISSUE THREAD

**Issue by gdbaldw** [modernweb-dev/rocket#197]
Clean install following current installation directions. ERROR.

I corrected this error with:

`touch docs/_data/footer.json`

So, it appears to be some issue with rocket preset of the footer.

Full error log here...
```
> rocket start

/home/doug/projects/demo-local-store/node_modules/@11ty/eleventy/src/TemplateData.js:353
        throw new TemplateDataParseError(
              ^

TemplateDataParseError: Having trouble parsing data file ./docs/_merged_data/footer.json
    at TemplateData._parseDataFile (/home/doug/projects/demo-local-store/node_modules/@11ty/eleventy/src/TemplateData.js:353:15)
    at async TemplateData.getAllGlobalData (/home/doug/projects/demo-local-store/node_modules/@11ty/eleventy/src/TemplateData.js:228:18)
    at async TemplateData.getData (/home/doug/projects/demo-local-store/node_modules/@11ty/eleventy/src/TemplateData.js:255:24)
    at async RocketCli.setupEleventy (file:///home/doug/projects/demo-local-store/node_modules/@rocket/cli/src/RocketCli.js:114:7)
    at async RocketCli.run (file:///home/doug/projects/demo-local-store/node_modules/@rocket/cli/src/RocketCli.js:158:5) {
  originalError: SyntaxError: Unexpected token ] in JSON at position 423
      at parse (<anonymous>)
      at TemplateData._parseDataFile (/home/doug/projects/demo-local-store/node_modules/@11ty/eleventy/src/TemplateData.js:351:16)
      at async TemplateData.getAllGlobalData (/home/doug/projects/demo-local-store/node_modules/@11ty/eleventy/src/TemplateData.js:228:18)
      at async TemplateData.getData (/home/doug/projects/demo-local-store/node_modules/@11ty/eleventy/src/TemplateData.js:255:24)
      at async RocketCli.setupEleventy (file:///home/doug/projects/demo-local-store/node_modules/@rocket/cli/src/RocketCli.js:114:7)
      at async RocketCli.run (file:///home/doug/projects/demo-local-store/node_modules/@rocket/cli/src/RocketCli.js:158:5)
}
```

**Comment by jorgecasar** [comment]
Thanks, I will fix ASAP. Meanwhile, you can override it creating your own footer.json without the comma of line 21

https://github.com/modernweb-dev/rocket/blob/main/packages/launch/preset/_data/footer.json#L21

**Comment by danihuge** [comment]
Thanks @jorgecasar 👏
