### ISSUE TITLE
[bug] Error on `rocket build` with a rollup plugin `TypeError: Cannot read properties of undefined (reading 'startsWith')` 

### ISSUE THREAD

**Issue by guillemcordoba** [modernweb-dev/rocket#430]
Steps to reproduce:

1. Run `npx @rocket/create@latest`, select the documentation theme.
2. Cd into that folder and run `npm install`.
3. Install `@rollup/plugin-json` with `npm i -D @rollup/plugin-json`.
4. Change `config/rocket.config.js`, adding the rollup json plugin as stated in [the documentation](https://rocket.modern-web.dev/docs/basics/configuration/#adding-rollup-plugins):
```
import json from '@rollup/plugin-json';
import { addPlugin } from 'plugins-manager';

/** @type {import('@rocket/cli').RocketCliOptions} */
export default {
  setupDevServerAndBuildPlugins: [addPlugin(json, { }, { location: 'top' })],
};
```
5. Run `npm run build`.

This is the error that shows up:

```
guillem@guillem-thinkpad:~/projects/lab/rocket-commonjs-plugin-repro$ npm run build

> rocket-docs-theme-launch@0.0.1 build
> rocket build

Engine building...
Generating Open Graph Images...
Optimize Production Build...
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at Object.transform (/home/guillem/projects/lab/rocket-commonjs-plugin-repro/node_modules/@web/dev-server-rollup/dist/rollupAdapter.js:228:30)
    at file:///home/guillem/projects/lab/rocket-commonjs-plugin-repro/node_modules/rollup/dist/es/shared/rollup.js:22717:40 {
  code: 'PLUGIN_ERROR',
  plugin: 'json',
  hook: 'transform',
  id: '/home/guillem/projects/lab/rocket-commonjs-plugin-repro/_site-dev/inline-module-ad21fcfbb3d325880e51446273377108.js',
  watchFiles: [
    '/home/guillem/projects/lab/rocket-commonjs-plugin-repro/_site-dev/404.html',
```

Here is a reproduction repository: https://github.com/guillemcordoba/rocket-commonjs-plugin-repro

**Comment by daKmoR** [comment]
Thanks for opening this issue and for helping improve Rocket.

Rocket has been rebuilt from a clean slate for the new `@rocket/js` release. The implementation, docs, APIs, and project structure have changed substantially, so the old issue history no longer maps cleanly to the current codebase.

I’m closing this as part of the repository reset.

This is currently a soft launch: the package and docs are live, and we’re dogfooding the new version on real projects before doing a larger public relaunch.

If this issue is still relevant with the new Rocket, please open a fresh issue against the current `main` branch with updated context.

Thanks again.
