### ISSUE TITLE
Error using RocketSearch without RocketLaunch

### ISSUE THREAD

**Issue by jorgecasar** [modernweb-dev/rocket#47]
Using `rocketSearch` like this in the rocket.config.js:

```js
import { rocketSearch } from '@rocket/search';
import { fireTheme } from './fire-theme/index.js';

export default {
  presets: [fireTheme(), rocketSearch()],
};
```

We get this error:

```bash
(node:94964) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '_site-dev/_merged_assets/_static/rocket-search-index.json'
    at Object.openSync (fs.js:476:3)
    at Object.writeFileSync (fs.js:1467:35)
    at RocketSearchPlugin.saveIndex (file:///[path-to-rocket-project]/node_modules/@rocket/search/src/RocketSearchPlugin.js:132:8)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RocketSearchPlugin.updated (file:///[path-to-rocket-project]/node_modules/@rocket/search/src/RocketSearchPlugin.js:118:5)
    at async RocketCli.update (file:///[path-to-rocket-project]/node_modules/@rocket/cli/src/RocketCli.js:185:9)
    at async RocketEleventy.write (file:///[path-to-rocket-project]/node_modules/@rocket/cli/src/RocketCli.js:33:5)
    at async RocketEleventy.watch (/[path-to-rocket-project]/node_modules/@11ty/eleventy/src/Eleventy.js:650:5)
    at async RocketStart.startCommand (file:///[path-to-rocket-project]/node_modules/@rocket/cli/src/RocketStart.js:43:7)
    at async RocketCli.run (file:///[path-to-rocket-project]/node_modules/@rocket/cli/src/RocketCli.js:132:9)
  ```

**Comment by daKmoR** [comment]
I don't think this is still applicable in the latest version using `@rocket/engine`? 🤔

I'm closing it - if it still needs fixing feel free to reopen or creating a new issue 🤗
